name: My First Devops Pipeline 
on: [push] # This tells the robot to wake up every time you push code

jobs:
  build-and-test:
    runs-on: ubuntu-latest # The robot starts a fresh Linux computer
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4  # The robot "downloads" your code to its computer

    - name: Say Hello
      run: echo "Hello! My Pipeline is running from VS Code!"

    - name: Show the date
      run: date 

    
      